<?xml version="1.0" encoding="utf-8"?>
<!-- Created by Leo: http://leoeditor.com/leo_toc.html -->
<leo_file xmlns:leo="http://leoeditor.com/namespaces/leo-python-editor/1.1" >
<leo_header file_format="2" tnodes="0" max_tnode_index="0" clone_windows="0"/>
<globals body_outline_ratio="0.5" body_secondary_ratio="0.5">
	<global_window_position top="50" left="50" height="500" width="700"/>
	<global_log_window_position top="0" left="0" height="0" width="0"/>
</globals>
<preferences/>
<find_panel_settings/>
<vnodes>
<v t="leo.20160128164022.1"><vh>在 Leo Editor 環境開發 Python 程式</vh></v>
<v t="leo.20160128180854.1"><vh>導入以 node.js 編寫的 ungit</vh></v>
<v t="leo.20160128180653.1"><vh>@button ungit</vh></v>
<v t="leo.20160128162108.2"><vh>@edit test.py</vh></v>
</vnodes>
<tnodes>
<t tx="leo.20160128164022.1">g.es() 等同 print() 會將資料印在 Log 區域

選擇 @edit, @clean 節點, 然後按下 Ctrl+b 就可以執行程式內容

但是所有出現在 Log pane 的所有資料都沒有空白區隔, 原因不明</t>
<t tx="leo.20160128180653.1">import os
os.system("y:/apps/start_ungit.bat")</t>
<t tx="leo.20160128180854.1">https://github.com/FredrikNoren/ungit</t>
</tnodes>
</leo_file>
